# Generated by Django 4.2.3 on 2023-07-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mileage',
            name='mileage',
            field=models.PositiveIntegerField(default=0, verbose_name='пробег'),
        ),
    ]
