# Generated by Django 4.2.3 on 2023-08-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_alter_mileage_mileage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mileage',
            options={'ordering': ('year',), 'verbose_name': 'пробег', 'verbose_name_plural': 'пробеги'},
        ),
        migrations.RenameField(
            model_name='car',
            old_name='title',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='motorcycle',
            old_name='title',
            new_name='model',
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='год'),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='year',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='год'),
        ),
    ]
