# Generated by Django 4.2.3 on 2023-08-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_car_owner_motorcycle_owner_alter_mileage_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.IntegerField(default=1000, verbose_name='цена'),
        ),
    ]
