# Generated by Django 4.2.3 on 2023-08-24 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0007_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mileage',
            name='motorcycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mileage', to='vehicle.motorcycle'),
        ),
    ]
